### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by akileez** [markschad/grunt-bower-linker#1]
with only jquery in the bower folder I get this error message:

```
Running "bower-linker:default" (bower-linker) task
Fatal error: Object.keys called on non-object
```

with only jquery and fitText I get this (this same error occurs with a full stack of files):

```
Running "bower-linker:default" (bower-linker) task
Linking [jquery.js]...
Linking [jquery.fittext.js]...
Fatal error: Object.keys called on non-object
```

I have the default setup as listed in your gruntfile. Any additional info needed, please advise.

**Comment by markschad** [comment]
I can't reproduce the error but it looks like it may be problem with [L61](https://github.com/markschad/grunt-bower-linker/blob/644e5ae895b2754145d1352a2d4855c35d5e413d/tasks/bower-linker.js#L61) of the task file.  Something returning null and Object.keys not being able to parse correctly.

I think I fixed this in the latest commit, let me know.

**Comment by akileez** [comment]
That did the trick. Thanks!

**Comment by markschad** [comment]
No problem!
